version: 0.2

env:
  variables:
    ASSUME_ACCOUNT: "837180165073"
    ASSUME_ROLE_ARN: "arn:aws:iam::837180165073:role/SharedAccAccessRole"
  #parameter-store:
   # AWS_ACCESS_KEY_ID: ""

phases:
  install:
    commands:
      - echo Setting up virtualenv
      - python -m venv venv
      - . venv/bin/activate
      - echo Installing requirements from file
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo Building and running tests
      - python tests.py
      - zip -r assumeRoleLayer.zip * --exclude venv/**\*
      - ls -l *.zip
  post_build:
    commands:
      - echo Build completed on `date`
      - echo '***** Uploading to S3 *****'
      - aws s3 sync assumeRoleLayer.zip s3://cops-codebuild-packages
      - echo Deployment completed

artifacts:
  primary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR
      files:
        - assumeRoleLayer.zip