version: 0.2

env:
  variables:
    ASSUME_ACCOUNT: "837180165073"
    ASSUME_ROLE_ARN: "arn:aws:iam::837180165073:role/SharedAccAccessRole"
  #parameter-store:
   # AWS_ACCESS_KEY_ID: ""

phases:
  install:
    commands:
      - echo Setting up virtualenv
      - python -m venv venv
      - . venv/bin/activate
      - echo Installing requirements from file
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - echo 'Working dir'
      - pwd
      - echo Building and running tests
      - python tests.py
      - zip -r /tmp/assumeRoleLayer.zip * --exclude venv/**\*
      - ls -l /tmp/*.zip
  post_build:
    commands:
      - echo Build completed on `date`
      - echo '***** SOURCE DIR *****'
      - echo $CODEBUILD_SRC_DIR
      - echo '***** Uploading to S3 *****'
      - aws s3 cp assumeRoleLayer.zip s3://cops-codebuild-packages/assumeRole.zip
      - echo Deployment completed

artifacts:
  base-directory: /tmp/
  files:
    - '*.zip'
  discard-paths: yes
# artifacts:
#   primary-artifacts:
#     artifact1:
#       base-directory: /tmp/
#       discard-paths: yes
#       files:
#         - '*'